// ReceitasData.js
// Base mockada de receitas/protocolos padronizados por queixa, extraída de prescrições
// próprias do usuário. Uso pessoal como referência rápida — SEMPRE reavaliar dose por
// peso/idade/função renal-hepática do paciente antes de reutilizar qualquer item.

export const RECEITAS = [
  {
    id: 'vitamina-d-b12',
    titulo: 'Suplementação preventiva de Vitamina D (até 18 anos) / Idoso / Vit. B12',
    faixaEtaria: 'geral',
    contexto: null,
    itens: [
      {
        nome: 'Vitamina D 200 UI',
        quantidade: '1',
        unidade: 'FRASCO',
        posologia: 'DAR 3 GOTAS UMA VEZ AO DIA, TODO DIA.',
        via: 'VO',
        controlado: false,
        obs: 'Pediátrico.',
      },
      {
        nome: 'Vitamina D 50.000 UI',
        quantidade: '8',
        unidade: 'CPR',
        posologia: 'TOMAR 1 COMPRIMIDO POR SEMANA, POR 8 SEMANAS.',
        via: 'VO',
        controlado: false,
        obs: 'Idoso.',
      },
      {
        nome: 'Mecobe (Vitamina B12)',
        quantidade: '1',
        unidade: 'CX',
        posologia: 'TOMAR 1 COMPRIMIDO SUBLINGUAL, AO DIA, POR 1 MÊS.',
        via: 'Sublingual',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'dor-febre-adulto',
    titulo: 'Dor / Febre — Adulto (esquema geral)',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Ibuprofeno 600 mg',
        quantidade: '10',
        unidade: 'CPR',
        posologia: 'TOMAR 01 COMPRIMIDO DE 12/12 HORAS POR 5 DIAS, SE DOR.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Nimesulida 100 mg',
        quantidade: '10',
        unidade: 'CPR',
        posologia: 'TOMAR 01 COMPRIMIDO C 12/12H POR 5 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Guaco Xarope (Mikania glomerata 0,05 mL/mL, 100 mL)',
        quantidade: '1',
        unidade: 'FRASCO',
        posologia: 'TOMAR 10 ML, VIA ORAL, DE 8/8 HORAS, POR 7 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Omeprazol 20 mg',
        quantidade: '30',
        unidade: 'CAP',
        posologia: 'TOMAR 1 COMPRIMIDO EM JEJUM POR 30 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Dipirona 500 mg',
        quantidade: '10',
        unidade: 'CPR',
        posologia: 'TOMAR 01 COMPRIMIDO DE 06/06H SE DOR OU FEBRE (ATÉ 3 DIAS).',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'hemorroidas-nauseas',
    titulo: 'Hemorroidas / Náuseas e vômitos',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Proctosan',
        quantidade: '1',
        unidade: 'TB',
        posologia: 'APLICAR EM REGIÃO AFETADA 2X DIA.',
        via: 'Tópico',
        controlado: false,
        obs: 'Hemorroidas.',
      },
      {
        nome: 'Domperidona 10 mg',
        quantidade: '1',
        unidade: 'CX',
        posologia: 'TOMAR 01 CP VO CADA 8 HRS.',
        via: 'VO',
        controlado: false,
        obs: 'Náuseas/vômitos.',
      },
    ],
  },
  {
    id: 'has-dislipidemia',
    titulo: 'Hipertensão + Dislipidemia (esquema geral)',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Losartana Potássica 50 mg',
        quantidade: '60',
        unidade: 'CPR',
        posologia: 'TOMAR 1 COMPRIMIDO DE 12/12 HORAS POR 30 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Hidroclorotiazida 25 mg',
        quantidade: '30',
        unidade: 'CPR',
        posologia: 'TOMAR 1 COMPRIMIDO PELA MANHÃ POR 30 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Ácido Acetilsalicílico 100 mg',
        quantidade: '30',
        unidade: 'CPR',
        posologia: 'TOMAR 1 COMPRIMIDO AO DIA APÓS O ALMOÇO POR 30 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Sinvastatina 40 mg',
        quantidade: '30',
        unidade: 'CPR',
        posologia: 'TOMAR 1 COMPRIMIDO À NOITE POR 30 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'ANLODIPINO - BESILATO 5 MG',
        via: 'VO',
        quantidade: '30',
        posologia: 'TOMAR 1 COMPRIMIDO ÀS 17H (CINCO HORAS DA TARDE)',
        controlado: false,
        unidade: 'CPR',
      },
      {
        nome: 'ENALAPRIL - 20 MG',
        via: 'VO',
        quantidade: '60',
        posologia: 'TOMAR 1 COMPRIMIDO MANHÃ E NOITE',
        controlado: false,
        unidade: 'CPR',
      },
    ],
  },
  {
    id: 'rinite-hipotireoidismo',
    titulo: 'Rinite alérgica/urticária + Hipotireoidismo',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Cetirizina 10 mg (manipulado)',
        quantidade: '30',
        unidade: 'CPR',
        posologia: 'TOMAR 1 COMPRIMIDO AO DIA POR 30 DIAS.',
        via: 'VO',
        controlado: false,
        obs: 'Manipulado.',
      },
      {
        nome: 'Levotiroxina 50 mcg',
        quantidade: '30',
        unidade: 'CPR',
        posologia: 'TOMAR 01 COMPRIMIDO EM JEJUM DIARIAMENTE POR 30 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'tept-insonia',
    titulo: 'TEPT / Insônia',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Mirtazapina 15 mg',
        quantidade: '30',
        unidade: 'COMPRIMIDO',
        posologia: 'TOMAR 1 COMPRIMIDO À NOITE POR 30 DIAS.',
        via: 'VO',
        controlado: true,
        obs: null,
      },
    ],
  },
  {
    id: 'enxaqueca',
    titulo: 'Crise aguda de enxaqueca / Cefaleia em salvas',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Sumatriptano 50 mg',
        quantidade: '4',
        unidade: 'CPR',
        posologia: 'TOMAR 1 COMPRIMIDO DURANTE A CRISE DE DOR DE CABEÇA.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'espasmo-muscular',
    titulo: 'Espasmo muscular doloroso',
    faixaEtaria: 'adulto',
    contexto: 'Relaxante muscular de ação central.',
    itens: [
      {
        nome: 'Ciclobenzaprina 5 mg',
        quantidade: '5',
        unidade: 'CPR',
        posologia: 'TOMAR 01 COMPRIMIDO À NOITE POR 5 NOITES.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'candidiase-vaginal',
    titulo: 'Candidíase vaginal',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Nistatina 25.000 UI/g creme vaginal, 60 g (c/ 7 aplicadores)',
        quantidade: '2',
        unidade: 'TB',
        posologia: 'APLICAR VIA VAGINAL À NOITE, DURANTE 15 DIAS.',
        via: 'Vaginal',
        controlado: false,
        obs: '2 tubos para 15 dias.',
      },
    ],
  },
  {
    id: 'menstruacao',
    titulo: 'Fluxo menstrual intenso / Cólica menstrual',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Transamin 250 mg',
        quantidade: '1',
        unidade: 'CX',
        posologia: 'TOMAR 02 CP VO CADA 8 HORAS SE FLUXO MENSTRUAL INTENSO, POR ATÉ 4 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Buscopan Composto',
        quantidade: '1',
        unidade: 'CX',
        posologia: 'TOMAR 01 CP VO CADA 8 HRS SE CÓLICA MENSTRUAL.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'constipacao',
    titulo: 'Constipação',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: '20BI Fibras',
        quantidade: '1',
        unidade: 'CX',
        posologia: 'TOMAR 1 SACHÊ POR DIA, POR 10 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Lactulose',
        quantidade: '1',
        unidade: 'FR',
        posologia: 'TOMAR 3 ML 1X AO DIA, POR 3 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'receita-azul-idoso',
    titulo: 'Receita azul + Suplementação cálcio/vit D (idoso)',
    faixaEtaria: 'idoso',
    contexto: null,
    itens: [
      {
        nome: 'Clonazepam 2 mg',
        quantidade: '30',
        unidade: 'CPR',
        posologia: 'TOMAR UM COMPRIMIDO VIA ORAL À NOITE POR 30 DIAS.',
        via: 'VO',
        controlado: true,
        obs: 'Apenas para registro (receita azul).',
      },
      {
        nome: 'Carbonato de Cálcio + Colecalciferol 600 mg + 400 UI',
        quantidade: '30',
        unidade: 'CPR',
        posologia: 'TOMAR 01 CP AO DIA, NO ALMOÇO POR 30 DIAS.',
        via: 'VO',
        controlado: false,
        obs: 'Variante 1 — dose única diária.',
      },
      {
        nome: 'Carbonato de Cálcio + Colecalciferol 600 mg + 400 UI',
        quantidade: '60',
        unidade: 'CPR',
        posologia: 'TOMAR 01 COMPRIMIDO APÓS O CAFÉ E 01 COMPRIMIDO APÓS A JANTA POR 30 DIAS.',
        via: 'VO',
        controlado: false,
        obs: 'Variante 2 — 2x/dia.',
      },
    ],
  },
  {
    id: 'autismo-fluoxetina',
    titulo: 'Autismo — Fluoxetina',
    faixaEtaria: 'pediatrico',
    contexto: null,
    itens: [
      {
        nome: 'Fluoxetina 10 mg (manipulado, cápsula)',
        quantidade: '30',
        unidade: 'CAPSULA',
        posologia: 'DAR 01 CÁPSULA DE MANHÃ, APÓS O CAFÉ DA MANHÃ POR 30 DIAS.',
        via: 'VO',
        controlado: true,
        obs: 'Manipulado.',
      },
      {
        nome: 'Fluoxetina 20 mg/mL (gotas)',
        quantidade: '1',
        unidade: 'FR',
        posologia: 'DAR 10 GOTAS, PELA MANHÃ.',
        via: 'VO',
        controlado: true,
        obs: 'Apresentação alternativa em gotas.',
      },
    ],
  },
  {
    id: 'artrose',
    titulo: 'Artrose',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Nimesulida 100 mg',
        quantidade: '10',
        unidade: 'CPR',
        posologia: 'TOMAR 01 COMPRIMIDO 12/12 HORAS POR 5 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Neomicina 10 g',
        quantidade: '1',
        unidade: 'TB',
        posologia: 'APLICAR NA REGIÃO AFETADA 3 VEZES AO DIA.',
        via: 'Tópico',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Artrodar 50 mg',
        quantidade: '30',
        unidade: 'CPR',
        posologia: 'TOMAR 1 COMPRIMIDO 1X AO DIA POR 30 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'amigdalite-adulto',
    titulo: 'Amigdalite — Adulto',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Amoxicilina 500 mg',
        quantidade: '21',
        unidade: 'CAP',
        posologia: 'TOMAR 01 COMPRIMIDO VIA ORAL DE 8/8 HORAS POR 7 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Nimesulida 100 mg',
        quantidade: '10',
        unidade: 'CPR',
        posologia: 'TOMAR 01 COMPRIMIDO 12/12 HORAS POR 5 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Dipirona 500 mg',
        quantidade: '10',
        unidade: 'CPR',
        posologia: 'TOMAR 01 COMPRIMIDO 6/6H, SE DOR OU FEBRE (ATÉ 3 DIAS).',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'amigdalite-pediatrica',
    titulo: 'Amigdalite — Pediatria',
    faixaEtaria: 'pediatrico',
    contexto:
      '⚠️ ATENÇÃO: o rascunho original desta receita mistura cálculos para duas crianças de pesos diferentes (23 kg e 30 kg). NÃO usar como template sem reconferir a dose de ibuprofeno pelo peso real do paciente antes de reutilizar — a posologia abaixo é a que constava registrada, mas o próprio cálculo aponta que pode estar subterapêutica dependendo do peso.',
    itens: [
      {
        nome: 'Ibuprofeno 50 mg/mL, sol. gotas, 30 mL',
        quantidade: '2',
        unidade: 'FR',
        posologia: 'DAR 30 GOTAS VO 8/8 HORAS POR 3 DIAS.',
        via: 'VO',
        controlado: false,
        obs: 'CONFERIR PESO: 30 gotas pode ficar abaixo da faixa terapêutica de 5–10 mg/kg/dose dependendo do paciente. Recalcular antes de reutilizar.',
      },
      {
        nome: 'Paracetamol 200 mg/mL sol. oral, 15 mL',
        quantidade: '1',
        unidade: 'FR',
        posologia: 'DAR 23 GOTAS VO CADA 6H SE DOR OU FEBRE.',
        via: 'VO',
        controlado: false,
        obs: 'Calculado para ~23 kg (≈10 mg/kg/dose, no piso da faixa terapêutica 10–15 mg/kg).',
      },
      {
        nome: 'Azitromicina 40 mg/mL pó p/ susp., 600 mg',
        quantidade: '2',
        unidade: 'FR',
        posologia: 'DAR 6 ML VO 1X DIA POR 5 DIAS.',
        via: 'VO',
        controlado: false,
        obs: 'Calculado para ~23 kg (10 mg/kg/dia).',
      },
    ],
  },
  {
    id: 'amigdalite-falha-terapeutica',
    titulo: 'Amigdalite — Falha terapêutica',
    faixaEtaria: 'geral',
    contexto: null,
    itens: [
      {
        nome: 'Prednisolona 3 mg/mL sol. oral, 100 mL',
        quantidade: '1',
        unidade: 'FR',
        posologia: 'DAR 8 ML 1X AO DIA POR 5 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Nistatina 100.000 UI/mL susp. oral, 50 mL',
        quantidade: '1',
        unidade: 'FR',
        posologia: 'FAZER BOCHECHO 6 ML DE 6/6H POR 7 DIAS.',
        via: 'Oral (bochecho)',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'dor-cronica',
    titulo: 'Dor crônica',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Amitriptilina 25 mg',
        quantidade: '30',
        unidade: 'CPR',
        posologia: 'TOMAR 01 COMPRIMIDO VIA ORAL À NOITE POR 30 DIAS.',
        via: 'VO',
        controlado: true,
        obs: null,
      },
    ],
  },
  {
    id: 'h-pylori',
    titulo: 'H. pylori — Terapia tripla (14 dias)',
    faixaEtaria: 'adulto',
    contexto:
      'IBP: Omeprazol 20 mg 1x/dia. Amoxicilina 1 g 12/12h (se alérgico à penicilina: Metronidazol 400 mg 12/12h). Claritromicina 500 mg 12/12h. Teste respiratório da ureia ou antígeno fecal: mínimo 4 semanas após término do ATB e 2 semanas sem IBP.',
    itens: [],
  },
  {
    id: 'h-pylori-pos-tratamento',
    titulo: 'H. pylori — Pós-tratamento com queixas persistentes + diarreia',
    faixaEtaria: 'geral',
    contexto: null,
    itens: [
      {
        nome: 'Sais para Reidratação Oral',
        quantidade: '10',
        unidade: 'ENV',
        posologia: 'DISSOLVER 1 SACHÊ EM 1 LITRO DE ÁGUA E TOMAR AO LONGO DO DIA.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Hidróxido de Alumínio + Magnésio + Dimeticona susp., 100 mL',
        quantidade: '2',
        unidade: 'FR',
        posologia: 'TOMAR 10 ML OU UMA COLHER DE SOPA APÓS CAFÉ, ALMOÇO E JANTAR.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Domperidona 10 mg',
        quantidade: '60',
        unidade: 'CPR',
        posologia: 'TOMAR 1 COMPRIMIDO, 30 MINUTOS ANTES DO ALMOÇO E JANTAR POR 30 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Omeprazol 20 mg',
        quantidade: '20',
        unidade: 'CAP',
        posologia: 'TOMAR 1 COMPRIMIDO EM JEJUM POR 20 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Sulfato de Zinco 4 mg/mL xarope, 100 mL',
        quantidade: '1',
        unidade: 'FR',
        posologia: 'TOMAR 10 ML VIA ORAL 1 VEZ AO DIA DURANTE 5 DIAS.',
        via: 'VO',
        controlado: false,
        obs: 'Diarreia pediátrica.',
      },
      {
        nome: 'Saccharomyces boulardii 200 mg',
        quantidade: '20',
        unidade: 'CAPS',
        posologia: '1 CP VO 12/12H POR 10 DIAS.',
        via: 'VO',
        controlado: false,
        obs: 'Adulto.',
      },
      {
        nome: 'Lactobacillus rhamnosus',
        quantidade: '1',
        unidade: 'FR',
        posologia: 'TOMAR 5 GOTAS AO DIA.',
        via: 'VO',
        controlado: false,
        obs: 'Pediátrico.',
      },
    ],
  },
  {
    id: 'dip',
    titulo: 'DIP (Doença Inflamatória Pélvica) — tratamento compartilhado com parceiro',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Ceftriaxona Sódica 1 g IM',
        quantidade: '1',
        unidade: 'AMP',
        posologia: 'APLICAR MEIA AMPOLA INTRAMUSCULAR.',
        via: 'IM',
        controlado: false,
        obs: 'Tratamento compartilhado com parceiro — meia ampola para cada.',
      },
      {
        nome: 'Doxiciclina 100 mg',
        quantidade: '28',
        unidade: 'CPR',
        posologia: 'TOMAR 01 CP VO CADA 12 HRS POR 14 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Metronidazol 250 mg',
        quantidade: '56',
        unidade: 'CPR',
        posologia: 'TOMAR 2 COMPRIMIDOS A CADA 12/12 HORAS, POR 14 DIAS.',
        via: 'VO',
        controlado: false,
        obs: 'Parceiro: tomar 2 comprimidos de 12/12h durante 7 dias (28 cpr). Total para casal: 84 cpr.',
      },
    ],
  },
  {
    id: 'depressao-dor-neuropatica',
    titulo: 'Depressão maior + Ansiedade / Dor neuropática (diabética)',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Donaren Retard 150 mg',
        quantidade: '30',
        unidade: 'CP',
        posologia: 'TOMAR 01 CP À NOITE POR 30 DIAS.',
        via: 'VO',
        controlado: true,
        obs: null,
      },
    ],
  },
  {
    id: 'pos-menopausa',
    titulo: 'Pós-menopausa',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Tibolona 2,5 mg',
        quantidade: '30',
        unidade: 'CPR',
        posologia: 'TOMAR 01 CP VO PELA MANHÃ POR 30 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'epilepsia',
    titulo: 'Epilepsia',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Lamotrigina 100 mg',
        quantidade: '30',
        unidade: 'CPR',
        posologia: 'TOMAR 1 COMPRIMIDO À NOITE, DIARIAMENTE POR 30 DIAS.',
        via: 'VO',
        controlado: true,
        obs: null,
      },
    ],
  },
  {
    id: 'desparasitacao',
    titulo: 'Desparasitação',
    faixaEtaria: 'geral',
    contexto: null,
    itens: [
      {
        nome: 'Albendazol 40 mg/mL susp. oral, 10 mL',
        quantidade: '5',
        unidade: 'FR',
        posologia: 'TOMAR 1 FRASCO UMA VEZ AO DIA POR 5 DIAS.',
        via: 'VO',
        controlado: false,
        obs: 'Pediátrico.',
      },
      {
        nome: 'Albendazol 400 mg (mastigável)',
        quantidade: '5',
        unidade: 'CPR',
        posologia: 'TOMAR 1 COMPRIMIDO POR DIA, DURANTE 5 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Secnidazol 1000 mg',
        quantidade: '4',
        unidade: 'CPR',
        posologia: 'TOMAR 2 COMPRIMIDOS, VIA ORAL, DOSE ÚNICA, REPETIR APÓS 21 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'conjuntivite-bacteriana',
    titulo: 'Conjuntivite bacteriana / infecção externa ocular',
    faixaEtaria: 'geral',
    contexto: null,
    itens: [
      {
        nome: 'Tobramicina 0,3% colírio, 5 mL',
        quantidade: '1',
        unidade: 'FR',
        posologia: 'PINGAR 1 GOTA NO OLHO AFETADO, 1X AO DIA POR 3 DIAS.',
        via: 'Ocular',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'ansiedade-depressao',
    titulo: 'Ansiedade / Depressão (controlados)',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Alprazolam 1 mg',
        quantidade: '30',
        unidade: 'COMPRIMIDO',
        posologia: 'TOMAR 1 COMPRIMIDO À NOITE POR 30 DIAS.',
        via: 'VO',
        controlado: true,
        obs: 'Receita azul — apenas para controle.',
      },
      {
        nome: 'Escitalopram 20 mg',
        quantidade: '30',
        unidade: 'COMPRIMIDO',
        posologia: 'TOMAR 1 (UM) COMPRIMIDO, VIA ORAL, PELA MANHÃ POR 30 DIAS.',
        via: 'VO',
        controlado: true,
        obs: null,
      },
    ],
  },
  {
    id: 'infeccao-pele',
    titulo: 'Infecções de pele',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Cefalexina 500 mg',
        quantidade: '28',
        unidade: 'CPR',
        posologia:
          'TOMAR 1 COMPRIMIDO ÀS 06H, 1 COMPRIMIDO ÀS 12H, 1 COMPRIMIDO ÀS 18H, 1 COMPRIMIDO À MEIA-NOITE. POR 7 DIAS.',
        via: 'VO',
        controlado: false,
        obs: 'Esquema 6/6h com horários fixos.',
      },
      {
        nome: 'Nimesulida 100 mg',
        quantidade: '10',
        unidade: 'CPR',
        posologia: 'TOMAR 01 COMPRIMIDO 12/12 HORAS POR 5 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'foliculite',
    titulo: 'Foliculite',
    faixaEtaria: 'geral',
    contexto: null,
    itens: [
      {
        nome: 'Neomicina 10 g',
        quantidade: '1',
        unidade: 'TB',
        posologia: 'APLICAR NA REGIÃO AFETADA 3 VEZES AO DIA.',
        via: 'Externo/Tópico',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'fraqueza-cansaco',
    titulo: 'Fraqueza / Cansaço',
    faixaEtaria: 'geral',
    contexto: null,
    itens: [
      {
        nome: 'Vitamina do Complexo B xarope, 100 mL',
        quantidade: '1',
        unidade: 'FR',
        posologia: 'TOMAR 10 ML POR DIA.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'alergia-cutanea-infeccao',
    titulo: 'Quadro alérgico (rinite/urticária/picada/dermatite) associado a infecção',
    faixaEtaria: 'geral',
    contexto: null,
    itens: [
      {
        nome: 'Amoxicilina 250 mg/5 mL pó p/ susp., 150 mL',
        quantidade: '1',
        unidade: 'FR',
        posologia: 'DAR ___ ML VO 12/12 HORAS POR 7 DIAS.',
        via: 'VO',
        controlado: false,
        obs: 'Volume não especificado no rascunho original — calcular por peso antes de usar.',
      },
      {
        nome: 'Ácido Ascórbico (Vit. C) 200 mg/mL sol., 20 mL',
        quantidade: '1',
        unidade: 'FR',
        posologia: 'TOMAR 13 GOTAS, UMA VEZ AO DIA, ANTES DO ALMOÇO.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Dexclorfeniramina 0,4 mg/mL sol. oral, 120 mL',
        quantidade: '1',
        unidade: 'FR',
        posologia: 'TOMAR 2,5 ML VO DE 8/8 HORAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Neomicina 10 g',
        quantidade: '2',
        unidade: 'TB',
        posologia: 'APLICAR NA REGIÃO AFETADA 3 VEZES AO DIA.',
        via: 'Externo/Tópico',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'hpb',
    titulo: 'Hiperplasia Prostática Benigna (HPB)',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Tansulosina 0,4 mg + Dutasterida 0,5 mg',
        quantidade: '30',
        unidade: 'CPR',
        posologia: 'TOMAR 1 COMPRIMIDO À NOITE POR 30 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'penicilina-benzatina-profilaxia',
    titulo: 'Profilaxia de Febre Reumática — Penicilina Benzatina',
    faixaEtaria: 'geral',
    contexto:
      'Dose por peso: 600.000 UI (<27 kg) ou 1.200.000 UI (≥27 kg). Alternativa VO: Amoxicilina 50 mg/kg/dia (máx 1 g) por 10 dias.',
    itens: [
      {
        nome: 'Benzilpenicilina Benzatina 1.200.000 UI + diluente 4 mL',
        quantidade: '1',
        unidade: 'AMP',
        posologia: 'APLICAR 1 AMPOLA, IM, EM GLÚTEO. DOSE ÚNICA A CADA 21 DIAS.',
        via: 'IM',
        controlado: false,
        obs: 'Esquema de profilaxia periódica (a cada 21 dias) — confirmar indicação de manutenção vs. dose única de tratamento agudo.',
      },
    ],
  },
  {
    id: 'dor-abdominal-pos-alimentar',
    titulo: 'Dor abdominal após ingestão de alimento',
    faixaEtaria: 'geral',
    contexto: null,
    itens: [
      {
        nome: 'Sais para Reidratação Oral',
        quantidade: '6',
        unidade: 'ENV',
        posologia: 'DISSOLVER 1 SACHÊ EM 1 LITRO DE ÁGUA E TOMAR AO LONGO DO DIA.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Omeprazol 20 mg',
        quantidade: '10',
        unidade: 'CAP',
        posologia: 'TOMAR 1 COMPRIMIDO EM JEJUM POR 10 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Sulfato de Zinco 4 mg/mL xarope, 100 mL',
        quantidade: '1',
        unidade: 'FR',
        posologia: 'TOMAR 10 ML VIA ORAL 1 VEZ AO DIA DURANTE 5 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'expectorante',
    titulo: 'Expectorante',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Acebrofilina 10 mg/mL adulto, 120 mL',
        quantidade: '1',
        unidade: 'FR',
        posologia: 'TOMAR 10 ML DE 12/12 HORAS POR 5 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'insonia-trazodona',
    titulo: 'Insônia — Trazodona',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Motraz (Trazodona) 50 mg',
        quantidade: '30',
        unidade: 'COMPRIMIDO',
        posologia: 'TOMAR 1 COMPRIMIDO À NOITE POR 30 DIAS.',
        via: 'VO',
        controlado: true,
        obs: null,
      },
    ],
  },
  {
    id: 'inicio-estatina-criterios',
    titulo: 'Critérios para início de estatina (referência — não é receita)',
    faixaEtaria: 'adulto',
    contexto:
      'Evento CV estabelecido (IAM, AVC, DAC, DAP prévios): estatina de alta potência. ' +
      'Risco baixo (<5%): estatina só se LDL muito alto (>190) ou fatores agravantes. ' +
      'Risco intermediário (5–20%): considerar estatina, principalmente com fatores agravantes (HF, PCR-us elevada, escore de cálcio >0). ' +
      'Risco alto (>20%) ou diabéticos/DRC/HF: estatina indicada, meta LDL <70 mg/dL. ' +
      'Risco muito alto (evento CV prévio): estatina de alta potência, meta LDL <50 mg/dL. ' +
      'Casos especiais: LDL ≥190 → estatina de alta potência; DM (>40 anos, ou com lesão de órgão-alvo/múltiplos fatores de risco); DRC (TFG <60).',
    itens: [],
  },
  {
    id: 'trigliceridemia-grave',
    titulo: 'Triglicerídeos > 500 mg/dL',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Ciprofibrato 100 mg',
        quantidade: '90',
        unidade: 'COMP',
        posologia: 'TOMAR 1 COMPRIMIDO POR DIA DURANTE 90 DIAS, APÓS REALIZAR NOVO EXAME E APRESENTAR NA UNIDADE DE SAÚDE.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
      {
        nome: 'Ômega 3 Vitafor',
        quantidade: '60',
        unidade: 'CAP',
        posologia: 'TOMAR 1 CÁPSULA POR DIA DURANTE 60 DIAS.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'dermatite-topica',
    titulo: 'Dermatite / lesão inflamatória tópica',
    faixaEtaria: 'geral',
    contexto: null,
    itens: [
      {
        nome: 'Dexametasona 0,1% creme, 10 g',
        quantidade: '1',
        unidade: 'TB',
        posologia: 'APLICAR NA LESÃO 2 VEZES AO DIA.',
        via: 'Externo/Tópico',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'espasmo-muscular-curto',
    titulo: 'Espasmo muscular — esquema curto (3 noites)',
    faixaEtaria: 'adulto',
    contexto: null,
    itens: [
      {
        nome: 'Ciclobenzaprina 5 mg',
        quantidade: '3',
        unidade: 'CPR',
        posologia: 'TOMAR 01 COMPRIMIDO À NOITE POR 3 NOITES.',
        via: 'VO',
        controlado: false,
        obs: null,
      },
    ],
  },
  {
    id: 'crise-asmatica-dpoc',
    titulo: 'Crise asmática / Broncoespasmo (DPOC)',
    faixaEtaria: 'geral',
    contexto:
      'Considerar prednisona se broncoespasmo moderado/francamente sintomático; se quadro leve, tentar apenas broncodilatador e reavaliar em 48h.',
    itens: [
      {
        nome: 'Salbutamol Sulfato 100 mcg/dose aerossol, 200 doses',
        quantidade: '1',
        unidade: 'FR',
        posologia: 'APLICAR 8 PUFFS 06/06 HORAS — PARA RESGATE.',
        via: 'Inalatória',
        controlado: false,
        obs: 'Variante registrada: 2 jatos 6/6h por 5 dias, preferencialmente com espaçador.',
      },
      {
        nome: 'Prednisona 20 mg',
        quantidade: '5',
        unidade: 'CPR',
        posologia: 'TOMAR 01 COMPRIMIDO AO DIA POR 5 DIAS.',
        via: 'VO',
        controlado: false,
        obs: 'Variante registrada: 40 mg (2 cp) VO 1x/dia por 5 dias.',
      },
    ],
  },
  {
    id: 'quetiapina',
    titulo: 'Quetiapina',
    contexto: 'Esquizofrenia / Transtorno Bipolar / Insônia',
    itens: [
      {
        nome: 'QUETROS 100MG',
        via: 'VO',
        quantidade: '60',
        posologia: 'TOMAR 1 COMPRIMIDO VO A NOITE',
        controlado: true,
        unidade: 'CPR',
      },
    ],
  },
  {
    id: 'haloperidol',
    titulo: 'Haloperidol',
    contexto: 'Psicose / Agitação / Antipsicótico',
    itens: [
      {
        nome: 'HALDOL 1 MG',
        via: 'VO',
        quantidade: '120',
        posologia: 'TOMAR 01 CP VO 12/ 12 H',
        controlado: true,
        unidade: 'CP',
      },
    ],
  },
  {
    id: 'risperidona',
    titulo: 'Risperidona',
    contexto: 'Esquizofrenia / Transtorno Bipolar / Autismo',
    itens: [
      {
        nome: 'RISS 3MG',
        via: 'VO',
        quantidade: '120',
        posologia: 'TOMAR 1 COMPRIMIDO VO 12/12H',
        controlado: true,
        unidade: 'CPR',
      },
      {
        nome: 'RISPERIDONA 3 MG',
        via: 'VO',
        quantidade: '90',
        posologia: 'TOMAR UM COMPRIMIDO A NOITE',
        controlado: true,
        unidade: 'COMPRIMIDO',
      },
    ],
  },
  {
    id: 'anticonvulsivante',
    titulo: 'Anticonvulsivante / Outros Medicamentos',
    contexto: 'Epilepsia / Dor Neuropática / Outros',
    itens: [
      {
        nome: 'OXCARBAZEPINA - 300 MG',
        via: 'VO',
        quantidade: '120',
        posologia: 'TOMAR 01 COMPRIMIDO PELA MANHÃ E 01 COMPRIMIDO A NOITE.',
        controlado: true,
        unidade: 'CPR',
      }
    ],
  },
  {
    id: 'endometriose',
    titulo: 'Endometriose',
    contexto: 'Endometriose / Tratamento Hormonal',
    itens: [
      {
        nome: 'ZOLADEX - 3,6 MG',
        via: 'SC',
        quantidade: '1',
        posologia: '1 VEZ NO MÊS',
        controlado: false,
        unidade: 'SERINGA',
      },
      {
        nome: 'PREGABALINA 150MG',
        via: 'VO',
        quantidade: '120',
        posologia: 'TOMAR 1 COMPRIMIDO VIA ORAL 12/12H',
        controlado: true,
        unidade: 'CPR',
      },
      {
        nome: 'PACO 500/7,5MG',
        via: 'VO',
        quantidade: '30',
        posologia: 'TOMAR 01 COMPRIMIDO DE 6/6H SE DOR INTENSA.',
        controlado: true,
        unidade: 'CPR',
      },
    ],
  },
];


export const CATEGORIAS_FAIXA_ETARIA = {
  adulto: 'Adulto',
  pediatrico: 'Pediátrico',
  idoso: 'Idoso',
  geral: 'Geral',
};